
CREATE SCHEMA KQC3001;
SET SCHEMA KQC3001;

drop table MASTERDATA;
drop table TRANSACTIONS;

  CREATE TABLE "TRANSACTIONS" (
  "TRANSACTION_ID" INTEGER, 
  "PRODUCT_ID" VARCHAR(6), 
  "CUSTOMER_ID" VARCHAR(4), 
  "CUSTOMER_NAME" VARCHAR(30), 
  "STORE_ID" VARCHAR(4), 
  "STORE_NAME" VARCHAR(20), 
  "T_DATE" DATE, 
  "QUANTITY" INTEGER);
  

  -- CREATE UNIQUE INDEX "TRANSACTIONS_PK" ON "TRANSACTIONS" ("TRANSACTION_ID");
  ALTER TABLE "TRANSACTIONS" ALTER COLUMN "TRANSACTION_ID" NOT NULL;
  ALTER TABLE "TRANSACTIONS" ALTER COLUMN "PRODUCT_ID" NOT NULL ;
  ALTER TABLE "TRANSACTIONS" ALTER COLUMN "CUSTOMER_ID" NOT NULL ;
  ALTER TABLE "TRANSACTIONS" ALTER COLUMN "CUSTOMER_NAME" NOT NULL ;
  ALTER TABLE "TRANSACTIONS" ALTER COLUMN "STORE_ID" NOT NULL ;
  ALTER TABLE "TRANSACTIONS" ALTER COLUMN "STORE_NAME" NOT NULL ;
  ALTER TABLE "TRANSACTIONS" ALTER COLUMN "T_DATE" NOT NULL ;
  ALTER TABLE "TRANSACTIONS" ALTER COLUMN "QUANTITY" NOT NULL ;
  ALTER TABLE "TRANSACTIONS" ADD CONSTRAINT "TRANSACTIONS_PK" PRIMARY KEY ("TRANSACTION_ID") ;
  
  CREATE TABLE "MASTERDATA" (
  "PRODUCT_ID" VARCHAR(6), 
  "PRODUCT_NAME" VARCHAR(30), 
  "SUPPLIER_ID" VARCHAR(5), 
  "SUPPLIER_NAME" VARCHAR(30), 
  "PRICE" float DEFAULT 0.0);


  -- CREATE UNIQUE INDEX "MASTERDATA_PK" ON MASTERDATA ("PRODUCT_ID");

  ALTER TABLE "MASTERDATA" ALTER COLUMN "PRODUCT_ID" NOT NULL ;
  ALTER TABLE "MASTERDATA" ALTER COLUMN "PRODUCT_NAME" NOT NULL ;
  ALTER TABLE "MASTERDATA" ALTER COLUMN "SUPPLIER_ID" NOT NULL ;
  ALTER TABLE "MASTERDATA" ALTER COLUMN "SUPPLIER_NAME" NOT NULL ;
  ALTER TABLE "MASTERDATA" ALTER COLUMN "PRICE" NOT NULL ;
  ALTER TABLE "MASTERDATA" ADD CONSTRAINT "MASTERDATA_PK" PRIMARY KEY ("PRODUCT_ID") ;

