
--FACT TABLE
DROP TABLE SALES;

--DIMENSION TABLES
DROP TABLE SUPPLIERS;
DROP TABLE DATES;
DROP TABLE STORES;
DROP TABLE PRODUCTS;
DROP TABLE CUSTOMERS;

CREATE TABLE SUPPLIERS(
    SUPPLIER_ID VARCHAR(5) PRIMARY KEY NOT NULL,
    SUPPLIER_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE DATES(
    DATE_ID DATE PRIMARY KEY NOT NULL,
    DD DECIMAL(2,0) NOT NULL CONSTRAINT DD_CK
        CHECK(DD >=1 AND DD <= 31),
    MM DECIMAL(2,0) NOT NULL CONSTRAINT MM_CK
        CHECK(MM >=1 AND MM <=12),
    QTR DECIMAL(1,0) NOT NULL CONSTRAINT QTR_CK
        CHECK(QTR >=1 AND QTR <= 4),
    YYYY DECIMAL(4,0) NOT NULL,
    WEEK_OF_YEAR DECIMAL(2,0) NOT NULL  CONSTRAINT WEEK_OF_YEAR_CK 
        CHECK (WEEK_OF_YEAR >= 1 AND WEEK_OF_YEAR <= 52),
    WEEKDAY VARCHAR(9) NOT NULL CONSTRAINT WEEKDAY_CK 
        CHECK (
            WEEKDAY IN ('SUNDAY','MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY','FRIDAY','SATURDAY')
        )
);

CREATE TABLE PRODUCTS(
    PRODUCT_ID VARCHAR(6) PRIMARY KEY NOT NULL,
    PRODUCT_NAME VARCHAR(30) NOT NULL
    
);

CREATE TABLE STORES(
    STORE_ID VARCHAR(4) PRIMARY KEY NOT NULL,
    STORE_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE CUSTOMERS(
    CUSTOMER_ID VARCHAR(4) PRIMARY KEY NOT NULL,
    CUSTOMER_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE SALES(
    TRANSACTION_ID DECIMAL(8,0) PRIMARY KEY NOT NULL, 
    PRODUCT_ID VARCHAR(6) NOT NULL, 
    SUPPLIER_ID VARCHAR(5) NOT NULL, 
    CUSTOMER_ID VARCHAR(4) NOT NULL, 
    STORE_ID VARCHAR(4) NOT NULL, 
    DATE_ID DATE NOT NULL, 
    TOTAL_SALE DECIMAL(6,2) NOT NULL, --ASSUME THE PRICE CAN GO HIGH UP TO $9999.99

    CONSTRAINT fk_PROD_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT fk_STORE_ID FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID),
    CONSTRAINT fk_DATE_ID FOREIGN KEY (DATE_ID) REFERENCES DATES(DATE_ID),
    CONSTRAINT fk_SUPPLIER_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    CONSTRAINT fk_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

commit;