connect 'jdbc:derby://localhost:1527/countdownDW;create=true;user=kqc3001;password=password';

create schema kqc3001;
set schema kqc3001;

--FACT TABLE
drop table SALES;
drop table SUPPLIERS;
drop table DATES;
drop table STORES;
drop table PRODUCTS;
DROP TABLE CUSTOMERS;

CREATE TABLE SUPPLIERS(
    SUPPLIER_ID VARCHAR(5) PRIMARY KEY NOT NULL,
    SUPPLIER_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE DATES(
    DATE_ID DATE PRIMARY KEY NOT NULL,
    DD DECIMAL(2,0) NOT NULL,
    MM DECIMAL(2,0) NOT NULL,
    QTR DECIMAL(2,0) NOT NULL,
    YYYY DECIMAL(4,0) NOT NULL,
    WEEK DECIMAL(2,0) NOT NULL
);

CREATE TABLE PRODUCTS(
    PRODUCT_ID VARCHAR(6) PRIMARY KEY NOT NULL,
    PRODUCT_NAME VARCHAR(30) NOT NULL
    
);

CREATE TABLE STORES(
    STORE_ID VARCHAR(4) PRIMARY KEY NOT NULL,
    STORE_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE CUSTOMERS(
    CUSTOMER_ID VARCHAR(4) PRIMARY KEY NOT NULL,
    CUSTOMER_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE SALES(
    TRANSACTION_ID DECIMAL(8,0) PRIMARY KEY NOT NULL, --9223372036854775807 (java.lang.Long.MAX_VALUE)
    PRODUCT_ID VARCHAR(6) NOT NULL, 
    SUPPLIER_ID VARCHAR(5) NOT NULL, 
    CUSTOMER_ID VARCHAR(4) NOT NULL, 
    STORE_ID VARCHAR(4) NOT NULL, 
    DATE_ID DATE NOT NULL, 
    TOTAL_SALE DECIMAL(6,2) NOT NULL, --ASSUME THE PRICE CAN GO HIGH UP TO $9999.99

    CONSTRAINT fk_PROD_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT fk_STORE_ID FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID),
    CONSTRAINT fk_DATE_ID FOREIGN KEY (DATE_ID) REFERENCES DATES(DATE_ID),
    CONSTRAINT fk_SUPPLIER_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    CONSTRAINT fk_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

